`%||%` <- function(x, y) {
  if (is.null(x)) y else x
}

# CI defaults
CI_DEFAULT_POINT_SIZE <- 2.2
CI_DEFAULT_LINE_WIDTH <- 0.6
CI_DEFAULT_ALPHA <- 0.9
CI_DEFAULT_SHAPE <- 19
CI_DEFAULT_REF_LINE <- 1
CI_EXPANSION_MULT <- 0.03
CI_EXPANSION_MULT_LEFT <- 0.01

# Diamond geometry
DIAMOND_MAX_HEIGHT_RATIO <- 0.32
DIAMOND_BASE_OFFSET <- 0.08
DIAMOND_SIZE_SCALE <- 0.035

# Summary adjustments
SUMMARY_POINT_SIZE_BOOST <- 0.6
SUMMARY_LINE_WIDTH_FACTOR <- 1.25
SUMMARY_LINE_WIDTH_MIN_BOOST <- 0.15
GROUP_TEXT_SIZE_BOOST <- 0.2

# Bar panel
BAR_DEFAULT_FILL <- "#a8c5b8"
BAR_ROW_HEIGHT_FRACTION <- 0.55

# Dot panel
DOT_DEFAULT_FILL <- "#ffffff"
DOT_DEFAULT_SHAPE <- 21
DOT_DEFAULT_POINT_SIZE <- 2.4

# Favors annotation
FAVORS_ARROW_Y_OFFSET <- 0.62
FAVORS_TEXT_Y_OFFSET <- 0.82
FAVORS_ARROW_SPAN <- 0.70
FAVORS_GAP_DEFAULT <- 0.08
FAVORS_ARROW_LINEWIDTH <- 0.25
FAVORS_ARROW_LENGTH_IN <- 0.06

# Axis theme
AXIS_LINE_WIDTH <- 0.3
AXIS_TICK_LENGTH_INCHES <- 0.1
AXIS_TEXT_MARGIN_TOP <- 4
AXIS_TITLE_SIZE_BOOST <- 0.2
AXIS_TITLE_MARGIN_TOP <- 6

# Reference line
REFLINE_WIDTH <- 0.4
REFLINE_LINETYPE <- 2

# Truncation arrows
ARROW_LENGTH_INCHES <- 0.08
ARROW_TYPE <- "closed"
ARROW_ANGLE <- 30
ARROW_LOG_OFFSET_FACTOR <- 0.12
ARROW_LINEAR_OFFSET_FACTOR <- 0.06
ARROW_FALLBACK_OFFSET <- 0.1

# Device size
DEFAULT_ROW_HEIGHT <- 0.38

# Theme defaults
DEFAULT_TEXT_COLOUR <- "#1f1f1f"
DEFAULT_HEADER_COLOUR <- "#1f1f1f"
DEFAULT_REFLINE_COLOUR <- "#9aa1a6"
DEFAULT_TEXT_SIZE <- 3.6
DEFAULT_HEADER_SIZE <- 3.8

# Hline defaults
HLINE_DEFAULT_COLOUR <- "#d9dde2"
HLINE_DEFAULT_LINEWIDTH <- 0.45

# Range fallbacks
RANGE_LOG_SHRINK <- 0.8
RANGE_LOG_EXPAND <- 1.2
RANGE_LINEAR_PAD <- 0.5

# Header group defaults
HEADER_GROUP_BORDER_COLOUR <- "#d0d7de"
HEADER_GROUP_BORDER_LINEWIDTH <- 0.4
